In [7]:
#1. Import necessary libraries
import glob
import pandas as pd
import xml.etree.ElementTree as ET #deal with XML format
import json
from datetime import datetime

In [3]:
#2. Create path for files
tmpfile = 'temp.tmp'
logfile = 'logfile.txt'
targetfile = 'transformed_data.csv'

In [5]:
#3. Sandbox for data to manifest
df = pd.read_csv('source1.csv') # turn into the object/instance of pandas
df

    name  height  weight
0   alex   65.78  112.99
1   ajay   71.52  136.49
2  alice   69.40  153.03
3   ravi   68.22  142.34
4    joe   67.79  144.30

In [25]:
tree = ET.parse('source1.xml')
#tree.find("person") #Iterate over elements in XML <Element 'person' at 0x000001B26BCDD350>
#tree.getroot() # <Element 'data' at 0x000001B26C8D71A0>
root = tree.getroot()
for person in root:
    name = person.find("name")
    print(name)

<Element 'name' at 0x000001B26C8FF740>
<Element 'name' at 0x000001B26C8FF880>
<Element 'name' at 0x000001B26C8FF9C0>
<Element 'name' at 0x000001B26C8FFB00>

In [26]:
for person in root:
    name = person.find("name").text
    print(name)

simon
jacob
cindy
ivan

In [27]:
#4. Extract functions:
def extract_from_csv(input_file):
    df = pd.read_csv(input_file)
    return df

def extract_from_json(input_file):
    df = pd.read_json(input_file, lines = True) #read line by line in json file
    return df

#Note, because xml is not supported in pandas, so we have to blueprint the DF columns, then append values
def extract_from_xml(input_file):
    df = pd.DataFrame(columns = ["name", "height", "weight"]) #blueprint the dataframe(table)
    tree = ET.parse(input_file) #parse str into instance/object of ET
    root = tree.getroot()
    for person in root:
        name = person.find("name").text #find to get into person element 
        height = float(person.find("height").text) #cast type
        weight = float(person.find("weight").text)
        df = df.append({"name": name, "height":height, "weight": weight}, ignore_index = True) #parameter is dictionary
    return df

In [44]:
#5. Synthesyzing Extract function:
def extract():
    extracted_data = pd.DataFrame(columns =["name", "height", "weight"])
    for csvfile in glob.glob("*.csv"):
        extracted_data = extracted_data.append(extract_from_csv(csvfile), ignore_index = True)
    for jsonfile in glob.glob("*.json"):
        extracted_data = extracted_data.append(extract_from_json(jsonfile), ignore_index = True)
    for xmlfile in glob.glob("*.xml"):
        extracted_data = extracted_data.append(extract_from_xml(xmlfile), ignore_index = True)
    return extracted_data

In [31]:
#6. Transform function:
def transform(data):
    data["height"] = round(data.height * 0.0254, 2)
    data["weight"] = round(data.weight * 0.45359237, 2)
    return data

In [32]:
#7. Load:
def load(targetfile, data_to_load):
    data_to_load.to_csv(targetfile)

In [35]:
now = datetime.now()
type(now)

datetime.datetime

In [41]:
#8. Track log:
def log(message): 
    timestamp_format = '%Y-%m-%d-%H:%M:%S'
    now = datetime.now()
    timestamp = now.strftime(timestamp_format) #strftime is a method of datetime.datetime instance
    with open("logfile.txt", "a") as f:
        f.write("At " + timestamp + " , " + message + '\n')

In [42]:
#9 Test case:
log("ETL Job Started")

In [45]:
log("Extract phase Started")
extracted_data = extract()
log("Extract phase Ended")

C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\4010817526.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_csv(csvfile), ignore_index = True)
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\4010817526.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_csv(csvfile), ignore_index = True)
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\4010817526.py:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_csv(csvfile), ignore_index = True)
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\4010817526.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_json(jsonfile), ignore_index = True)
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\4010817526.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_json(jsonfile), ignore_index = True)
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\4010817526.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_json(jsonfile), ignore_index = True)
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\3380216058.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"name": name, "height":height, "weight": weight}, ignore_index = True) #parameter is dictionary
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\3380216058.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"name": name, "height":height, "weight": weight}, ignore_index = True) #parameter is dictionary
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\3380216058.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"name": name, "height":height, "weight": weight}, ignore_index = True) #parameter is dictionary
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\3380216058.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"name": name, "height":height, "weight": weight}, ignore_index = True) #parameter is dictionary
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\4010817526.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_xml(xmlfile), ignore_index = True)
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\3380216058.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"name": name, "height":height, "weight": weight}, ignore_index = True) #parameter is dictionary
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\3380216058.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"name": name, "height":height, "weight": weight}, ignore_index = True) #parameter is dictionary
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\3380216058.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"name": name, "height":height, "weight": weight}, ignore_index = True) #parameter is dictionary
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\3380216058.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"name": name, "height":height, "weight": weight}, ignore_index = True) #parameter is dictionary
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\4010817526.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_xml(xmlfile), ignore_index = True)
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\3380216058.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"name": name, "height":height, "weight": weight}, ignore_index = True) #parameter is dictionary
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\3380216058.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"name": name, "height":height, "weight": weight}, ignore_index = True) #parameter is dictionary
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\3380216058.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"name": name, "height":height, "weight": weight}, ignore_index = True) #parameter is dictionary
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\3380216058.py:17: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append({"name": name, "height":height, "weight": weight}, ignore_index = True) #parameter is dictionary
C:\Users\vagy1255\AppData\Local\Temp\ipykernel_4892\4010817526.py:9: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  extracted_data = extracted_data.append(extract_from_xml(xmlfile), ignore_index = True)

In [46]:
log("Transform phase Started")
transformed_data = transform(extracted_data)
log("Transform phase Ended")
transformed_data

     name  height  weight
0    alex    1.67   51.25
1    ajay    1.82   61.91
2   alice    1.76   69.41
3    ravi    1.73   64.56
4     joe    1.72   65.45
5    alex    1.67   51.25
6    ajay    1.82   61.91
7   alice    1.76   69.41
8    ravi    1.73   64.56
9     joe    1.72   65.45
10   alex    1.67   51.25
11   ajay    1.82   61.91
12  alice    1.76   69.41
13   ravi    1.73   64.56
14    joe    1.72   65.45
15  simon    1.72   50.97
16  jacob    1.70   54.73
17  cindy    1.69   57.81
18   ivan    1.72   51.77
19  simon    1.72   50.97
20  jacob    1.70   54.73
21  cindy    1.69   57.81
22   ivan    1.72   51.77
23  simon    1.72   50.97
24  jacob    1.70   54.73
25  cindy    1.69   57.81
26   ivan    1.72   51.77

In [47]:
log("Load phase Started")
load(targetfile,transformed_data)
log("Load phase Ended")

In [48]:
log("ETL Job Ended")