In [135]:
handle_excel.close()

In [1]:
from docxtpl import DocxTemplate
import pandas as pd
doc_1 = DocxTemplate("Word.docx")
doc_2 = DocxTemplate("Word2.docx")

In [2]:
from vietnam_number import n2w
number= '121984314'
n2w(number)

'một trăm hai mươi mốt triệu chín trăm tám mươi bốn nghìn ba trăm mười bốn'

In [3]:
handle_excel = pd.ExcelFile("Excel.xlsx")
data = handle_excel.parse('Sheet1')
data.head(5)

,No,Date,Code,gender,Gender,AD Code,AD_Name,Grade1,Grade,Grade2,...,Last Working\nDate,Add,Contract_No,Contract_Date,Paid,Holding,Total,Day,Month,Year
0,13,2023-10-06,13/2023/THKT-PHL-AD,chị,Chị,AD790,Ngô Thị Bích Hồng,SZD,Giám đốc Kinh doanh Khu vực Cấp cao,Giám đốc Kinh doanh Khu vực/ Giám đốc Kinh doa...,...,2023-09-30,"Tổ 2, xã Xuân Thọ, H. Xuân Lộc, tỉnh Đồng Nai",328/2022/LC,01/10/2022,219052575,0,0,6,10,2023
1,14,2023-10-06,14/2023/THKT-PHL-AD,anh,Anh,AD081,Bùi Thiên Xúy,RAD,Phó Giám đốc Kinh doanh Vùng,Phó Giám đốc Kinh doanh Vùng/ Giám đốc Kinh do...,...,2023-10-31,"25/12/26 Bùi Quang Là, Phường 12, Quận Gò Vấp,...",186/2023/LC,01/04/2023,591397458,0,0,6,10,2023
2,15,2023-10-06,15/2023/THKT-PHL-AD,chị,Chị,NaN,Nguyễn Thị Trúc Mai,RAD,Phó Giám đốc Kinh doanh Vùng,Phó Giám đốc Kinh doanh Vùng/ Giám đốc Kinh do...,...,NaT,"446/21/11 Thới An 28, KP.2, Phường Thới An, Qu...",429/2023/LC,06/07/2023,333394621,337754694,671149315,6,10,2023
3,16,2023-10-06,16/2023/THKT-PHL-AD,chị,Chị,A1270,Nguyễn Đặng Hoài Thương,ZD,Giám đốc Kinh doanh Khu vực,Giám đốc Kinh doanh Khu vực/ Giám đốc Kinh doa...,...,2023-10-31,"551 Hoàng Sa, Phường Võ Thị Sáu, Quận 3, TP. H...",304/2023/LC,22/05/2023,106745822,0,0,6,10,2023

In [11]:
#Xóa dấu tiếng Việt để đưa vào dòng chuyển khoản ngân hàng
BANG_XOA_DAU_FULL = str.maketrans(
    "ÁÀẢÃẠĂẮẰẲẴẶÂẤẦẨẪẬĐÈÉẺẼẸÊẾỀỂỄỆÍÌỈĨỊÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÚÙỦŨỤƯỨỪỬỮỰÝỲỶỸỴáàảãạăắằẳẵặâấầẩẫậđèéẻẽẹêếềểễệíìỉĩịóòỏõọôốồổỗộơớờởỡợúùủũụưứừửữựýỳỷỹỵ",
    "A"*17 + "D" + "E"*11 + "I"*5 + "O"*17 + "U"*11 + "Y"*5 + "a"*17 + "d" + "e"*11 + "i"*5 + "o"*17 + "u"*11 + "y"*5,
    chr(774) + chr(770) + chr(795) + chr(769) + chr(768) + chr(777) + chr(771) + chr(803) # 8 kí tự dấu dưới dạng unicode chuẩn D
)

def xoa_dau_full(txt: str) -> str:
    return txt.translate(BANG_XOA_DAU_FULL)

In [14]:
#Phải run cái này trước để tránh mất format của cột Amount ở kiểu number
data['Amount_Word'] = pd.Series([n2w(str(number)).capitalize() for number in data['Paid']])
#làm tròn số
data['Paid'] = pd.Series([int(number) for number in data['Paid']])
data['Holding'] = pd.Series([int(number) for number in data['Holding']])
data['Total'] = pd.Series([int(number) for number in data['Total']])
data

,No,Date,Code,gender,Gender,AD Code,AD_Name,Grade1,Grade,Grade2,...,Add,Contract_No,Contract_Date,Paid,Holding,Total,Day,Month,Year,Amount_Word
0,13,2023-10-06,13/2023/THKT-PHL-AD,chị,Chị,AD790,Ngô Thị Bích Hồng,SZD,Giám đốc Kinh doanh Khu vực Cấp cao,Giám đốc Kinh doanh Khu vực/ Giám đốc Kinh doa...,...,"Tổ 2, xã Xuân Thọ, H. Xuân Lộc, tỉnh Đồng Nai",328/2022/LC,01/10/2022,219052575,0,0,6,10,2023,Hai trăm mười chín triệu không trăm năm mươi h...
1,14,2023-10-06,14/2023/THKT-PHL-AD,anh,Anh,AD081,Bùi Thiên Xúy,RAD,Phó Giám đốc Kinh doanh Vùng,Phó Giám đốc Kinh doanh Vùng/ Giám đốc Kinh do...,...,"25/12/26 Bùi Quang Là, Phường 12, Quận Gò Vấp,...",186/2023/LC,01/04/2023,591397458,0,0,6,10,2023,Năm trăm chín mươi mốt triệu ba trăm chín mươi...
2,15,2023-10-06,15/2023/THKT-PHL-AD,chị,Chị,NaN,Nguyễn Thị Trúc Mai,RAD,Phó Giám đốc Kinh doanh Vùng,Phó Giám đốc Kinh doanh Vùng/ Giám đốc Kinh do...,...,"446/21/11 Thới An 28, KP.2, Phường Thới An, Qu...",429/2023/LC,06/07/2023,333394621,337754694,671149315,6,10,2023,Ba trăm ba mươi ba triệu ba trăm chín mươi bốn...
3,16,2023-10-06,16/2023/THKT-PHL-AD,chị,Chị,A1270,Nguyễn Đặng Hoài Thương,ZD,Giám đốc Kinh doanh Khu vực,Giám đốc Kinh doanh Khu vực/ Giám đốc Kinh doa...,...,"551 Hoàng Sa, Phường Võ Thị Sáu, Quận 3, TP. H...",304/2023/LC,22/05/2023,106745822,0,0,6,10,2023,Một trăm lẽ sáu triệu bảy trăm bốn mươi lăm ng...

In [15]:
#ỏ đây đã thành string
data['Paid'] = pd.Series([f'{number:,}'.replace(",",".") for number in data['Paid']])
data['Holding'] = pd.Series([f'{number:,}'.replace(",",".") for number in data['Holding']])
data['Total'] = pd.Series([f'{number:,}'.replace(",",".") for number in data['Total']])

In [16]:
data['Amount_Word'] = pd.Series([word.replace("lẽ","lẻ") for word in data['Amount_Word']])

In [ ]:
data

In [17]:
for index, row in data.iterrows():
    if row['Holding'] != '0':
        context = { 
            'Code': row['Code'],
            'Gender' : row['Gender'],
            'AD_Name' : row['AD_Name'],
            'AD_Name_Eng': xoa_dau_full(row['AD_Name']),
            'Add': row['Add'],
            'Grade': row['Grade'],
            'Grade2': row['Grade2'],
            'date': row['Day'],
            'month': row['Month'],
            'year': row['Year'],
            'Contract_No': row['Contract_No'],
            'Contract_Date': row['Contract_Date'],
            'Paid' : row['Paid'],
            'Holding': row['Holding'],
            'Total': row['Total'],
            'Amount_Word': row['Amount_Word'],
            'gender': row['gender']
                    }
        doc_2.render(context)
        doc_2.save(f"result/{row['Grade']}-{row['AD_Name']}.docx")
    else:
        context = { 
            'Code': row['Code'],
            'Gender' : row['Gender'],
            'AD_Name' : row['AD_Name'],
            'AD_Name_Eng': xoa_dau_full(row['AD_Name']),
            'Add': row['Add'],
            'Grade': row['Grade'],
            'Grade2': row['Grade2'],
            'date': row['Day'],
            'month': row['Month'],
            'year': row['Year'],
            'Contract_No': row['Contract_No'],
            'Contract_Date': row['Contract_Date'],
            'Paid' : row['Paid'],
            'Amount_Word': row['Amount_Word'],
            'gender': row['gender']
                    }
        doc_1.render(context)
        doc_1.save(f"result/{row['Grade']}-{row['AD_Name']}.docx")

In [148]:
print_to_word('2023-10-06')

0